<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxxisko\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxxisko/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPxxisko.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPxxisko\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPxxisko\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pxxisko',
    'container.build_id' => 'ee94950d',
    'container.build_time' => 1523275257,
));
